baseURL = 'https://aryido.github.io/'
languageCode = 'zh-tw'
title = 'Aryido'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[params]
  author = "Aryido"
  description = "My note"
  background_color_class = "bg-black"
  recent_posts_number = 3
